model:
    value: single_edit
mpnn:
    value: graph_feat
mpn_size:
    value: 64
depth:
    value: 3
dropout_mpn:
    value: 0.3
mlp_size:
    value: 128
dropout_mlp:
    value: 0.3
rnn_type:
    value: gru
clip_norm:
    value: 2.5
loss_type:
    value: softmax
edits_type:
    value: bond_edits
lr:
    value: 0.00025
pos_weight:
    value: 1.0
propagate_logits:
    value: true
print_every:
    value: 200
eval_every:
    value: 300
scheduler_type:
    value: plateau
anneal_rate:
    value: 0.9
metric_thresh:
    value: 0.01
patience:
    value: 10
epochs:
    value: 400
use_prod_edits:
    value: true
