model:
    value: lg_ind
mpnn:
    value: graph_feat
rnn_type:
    value: gru
mpn_size:
    value: 100
depth:
    value: 3
dropout_mpn:
    value: 0.15
embed_size:
    value: 50
mlp_size:
    value: 100
dropout_mlp:
    value: 0.3
clip_norm:
    value: 2.0
scheduler_type:
    value: plateau
metric_thresh:
    value: 0.01
patience:
    value: 5
anneal_rate:
    value: 0.9
lr:
    value: 0.0002
use_rxn_class:
    value: False
use_h_labels:
    value: True
use_grad_noise:
    value: True
use_prev_pred:
    value: True
print_every:
    value: 200
eval_every:
    value: 4500
epochs:
    value: 100
